all:
  vars:
    ansible_user: root

  children:

    vrouters:
      hosts:
        vrouter-01:
          ansible_host: 10.1.93.71
        vrouter-02:
          ansible_host: 10.1.93.73
        vrouter-03:
          ansible_host: 10.1.93.75
        vrouter-04:
          ansible_host: 10.1.93.77

    control_planes:
      hosts:
        cp-01:
          ansible_host: 192.168.51.20
        cp-02:
          ansible_host: 192.168.52.20
        cp-03:
          ansible_host: 192.168.53.20

    workers:
      hosts:
        worker-01:
          ansible_host: 192.168.51.30
        worker-02:
          ansible_host: 192.168.52.30

    database:
      children:

        mariadb_master:
          hosts:
            mariadb-01:
              ansible_host: 192.168.52.40

        mariadb_replica:
          hosts:
            mariadb-02:
              ansible_host: 192.168.51.40

        maxscale:
          hosts:
            maxscale-01:
              ansible_host: 192.168.53.40

    loadbalancer:
      hosts:
        lb-01:
          ansible_host: 10.1.93.78

    registry:
      hosts:
        harbor:
          ansible_host: 192.168.53.61

    storage:
      hosts:
        nfs:
          ansible_host: 192.168.54.50

    ansible_controller:
      hosts:
        ansible:
          ansible_host: 192.168.54.70
          ansible_connection: local