---
# ============================================================
# LB 기본 네트워크
# ============================================================

lb_management_ip: "10.1.93.78"

lb_vip: "10.1.93.90"
lb_vip_prefix: 24


# ============================================================
# LB Static Routes
# ============================================================

lb_static_routes:
  - network: 192.168.51.0/24
    gateway: 10.1.93.71

  - network: 192.168.52.0/24
    gateway: 10.1.93.73

  - network: 192.168.53.0/24
    gateway: 10.1.93.75

  - network: 192.168.54.0/24
    gateway: 10.1.93.77
    