---
# ============================================================
# Project VM Host Aliases
#
# ip    = 실제 서버 IP
# alias = 팀원들이 SSH 접속할 때 사용할 고정 별칭
#
# 실제 VM hostname과는 독립적으로 관리한다.
# hostname이 변경되어도 alias는 그대로 사용할 수 있다.
# ============================================================

common_host_entries:

  # ----------------------------------------------------------
  # Server-01
  # ----------------------------------------------------------

  - ip: 10.1.93.71
    alias: vr1  
  
  - ip: 192.168.51.20
    alias: cp1

  - ip: 192.168.51.30
    alias: wk1

  - ip: 192.168.51.40
    alias: db2


  # ----------------------------------------------------------
  # Server-02
  # ----------------------------------------------------------

  - ip: 10.1.93.73
    alias: vr2

  - ip: 192.168.52.20
    alias: cp2

  - ip: 192.168.52.30
    alias: wk2

  - ip: 192.168.52.40
    alias: db1


  # ----------------------------------------------------------
  # Server-03
  # ----------------------------------------------------------
  
  - ip: 10.1.93.75
    alias: vr3

  - ip: 192.168.53.20
    alias: cp3

  - ip: 192.168.53.40
    alias: ms1

  - ip: 192.168.53.61
    alias: hb

  - ip: 10.1.93.78
    alias: lb1


  # ----------------------------------------------------------
  # Server-04
  # ----------------------------------------------------------

  - ip: 10.1.93.77
    alias: vr4

  - ip: 192.168.54.50
    alias: nfs

  - ip: 192.168.54.70
    alias: ans